language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"

addons:
  apt:
    packages:
      - postgresql-10

env:
  global:
    - PGPORT=5433 # Start travis instance of postgress with this port so local docker configuration will not conflict.
