# Generated by Django 2.1.8 on 2019-04-18 18:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=-5192, help_text='A country code and phone number', max_length=128),
            preserve_default=False,
        ),
    ]
